---
- name: "Template git config"
  include_role:
    name: dotfiles-generic-template-role
  vars:
    template_root: "{{ root_dir }}"
    template_path: ".gitconfig"
  when: user_name and user_email

